version: '3.8'
services:
  db:
    image: postgres:14
    # データの永続化の為に使用
    volumes:
      - dbvolume:/var/lib/postgresql/data
    # Mac(M1)を使用している場合、platformに関するエラーが発生する可能性がある。エラー発生してから追加するのも良し。
    # platform: linux/x86_64
    env_file: .env
    ports:
      - '5433:5432'
  web:
    # 作成済みのDockerfileを元にコンテナを作成
    build:
      # Dockerfileでファイルの読み込み先を指定
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - gem_data:/usr/local/bundle
    ports:
      - '3000:3000'
    # コンテナの立ち上げ順と依存関係を指定。dbコンテナが立ち上がってからwebコンテナが立ち上がるようにする。
    depends_on:
      - db
    env_file: .env
    # stdin_open, ttyは`pry-byebug`を使用するために記述
    # stdin_open: true
    # tty: true
volumes:
  dbvolume:
  gem_data:
