version: '3.8'
services:
  db:
    image: postgres:14
    # データの永続化の為に使用
    volumes:
      - dbvolume:/var/lib/postgresql/data
    # Mac(M1)を使用している場合、platformに関するエラーが発生する可能性がある。エラー発生してから追加するのも良し。
    # platform: linux/x86_64
    env_file: .env
    ports:
      - '5432:5432'
  api:
    # 作成済みのDockerfileを元にコンテナを作成
    build: .
    # command: bundle exec puma -C config/puma.rb
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/api
      - gem_data:/usr/local/bundle
      - public-data:/api/public
      - tmp-data:/api/tmp
      - log-data:/api/log
    ports:
      - '3000:3000'
    # コンテナの立ち上げ順と依存関係を指定。dbコンテナが立ち上がってからwebコンテナが立ち上がるようにする。
    depends_on:
      - db
    env_file: .env
    # stdin_open, ttyは`pry-byebug`を使用するために記述
    tty: true
    stdin_open: true
  web:
    container_name: web
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - public-data:/api/public
      - tmp-data:/api/tmp
    ports:
      - '80:80'
    depends_on:
      - api
    tty: true
    stdin_open: true
volumes:
  dbvolume:
  gem_data:
  public-data:
  tmp-data:
  log-data:
